### ISSUE TITLE
node-gdal builds fail on almost everything during make

### ISSUE THREAD

**Issue by cigzigwon** [andrewl/gatsby-source-geo#2]
This is useless in any new project RN

**Comment by andrewl** [comment]
Thanks for your feedback @cigzigwon - seems like gdal 0.9 is broken, so I updated the dependency. Seems to work ok for me on the latest version of gatsby. lmk how you get on!

Thanks again,

Andrew

**Comment by cigzigwon** [comment]
@andrewl Sorry for sounding so bleak. I was hopeful. Much thanks! So much under the hood changed since that version of gdal.
